/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    'Introduction',
    {
      "type": 'category',
      "label": 'Protocol Overview',
      items: [
        "Protocol Overview/Protocol Overview",
        "Protocol Overview/Farming",
        { 
          type: 'category',
          label: 'Rewards',
          items: [
            {
              type: 'autogenerated',
              dirName: 'Protocol Overview/Rewards'
            }
          ]
        },
        "Protocol Overview/Governance"
      ],
    },
    {
      "type": 'category',
      "label": 'System Overview',
      items: [
        'System Overview/System Overview',
        'System Overview/Diamond',
        'System Overview/Sdex',
        'System Overview/Token Farm',
        'System Overview/Vault',
        { 
          type: 'category',
          label: 'Rewards',
          items: [
            {
              type: 'autogenerated',
              dirName: 'System Overview/Rewards'
            }
          ]
        },
        'System Overview/Governance'
      ]
    },
    {
      "type": 'category',
      "label": 'API Reference',
      items: [
        {
          type: 'autogenerated',
          dirName: 'API Specification'
        }
      ]
    }
  ]

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
};

module.exports = sidebars;
